language: php

php:
  - 5.6

install:
  #- composer install
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit -c module/RobotCafe/test/phpunit.xml --coverage-text
